"""Fetch Google Scholar citation stats and write to _data/scholar.yml."""
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import requests
from bs4 import BeautifulSoup

SCHOLAR_ID = os.environ.get("SCHOLAR_ID", "6F85yPcAAAAJ")
OUTPUT = Path(__file__).resolve().parent.parent / "_data" / "scholar.yml"

HEADERS = {
    "User-Agent": (
        "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "en-US,en;q=0.9",
}


def fetch_stats():
    url = f"https://scholar.google.com/citations?user={SCHOLAR_ID}&hl=en"
    resp = requests.get(url, headers=HEADERS, timeout=30)
    resp.raise_for_status()

    soup = BeautifulSoup(resp.text, "html.parser")
    cells = soup.select("td.gsc_rsb_std")
    if len(cells) < 5:
        print(f"ERROR: Unexpected page structure, found {len(cells)} cells")
        print("Page snippet:", resp.text[:500])
        sys.exit(1)

    return {
        "citations_all": int(cells[0].text),
        "citations_5y": int(cells[1].text),
        "h_index_all": int(cells[2].text),
        "h_index_5y": int(cells[3].text),
        "i10_index_all": int(cells[4].text),
        "i10_index_5y": int(cells[5].text) if len(cells) > 5 else 0,
    }


def write_yaml(stats):
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        f"# Auto-generated by fetch_scholar.py — do not edit manually",
        f"updated: \"{now}\"",
        f"scholar_id: \"{SCHOLAR_ID}\"",
    ]
    for key, val in stats.items():
        lines.append(f"{key}: {val}")

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUTPUT}")
    for key, val in stats.items():
        print(f"  {key}: {val}")


if __name__ == "__main__":
    stats = fetch_stats()
    write_yaml(stats)
